# Generated by Django 5.2.3 on 2025-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(default='slug', max_length=20, unique=True),
        ),
    ]
